FROM centos:6
RUN curl https://dl.google.com/go/go1.12.7.linux-amd64.tar.gz > go1.12.7.linux-amd64.tar.gz && tar -xzf go1.12.7.linux-amd64.tar.gz && mv go /usr/local
RUN yum -y install git
RUN yum -y install gcc

ENV GOPATH=/go
ENV PATH=/usr/local/go/bin:$GOPATH/bin:$PATH

RUN go get gopkg.in/goracle.v2
RUN go get github.com/hamptonjt/learning_go/banner_programs/asucommon
WORKDIR /go/src/github.com/hamptonjt/learning_go/banner_programs
RUN yum -y install vim
# RUN cd azgaorp && go build -o azgaorp . && cd ../rzidlfr && go build -o rzidlfr .
